// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURXd589TMQgpzByJbx_ChmdfD1x9QCkg',
    appId: '1:1078431765304:android:0a0b7aef62bda53ab127cd',
    messagingSenderId: '1078431765304',
    projectId: 'flutter-chat-2b883',
    storageBucket: 'flutter-chat-2b883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk3n9rf8CI4cVzP8sG6wcE_EcZRlhfHRo',
    appId: '1:1078431765304:ios:356552ca97d13cf6b127cd',
    messagingSenderId: '1078431765304',
    projectId: 'flutter-chat-2b883',
    storageBucket: 'flutter-chat-2b883.appspot.com',
    iosClientId: '1078431765304-pehp0d36ns7t7bm1hvl6f4j62928fo4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk3n9rf8CI4cVzP8sG6wcE_EcZRlhfHRo',
    appId: '1:1078431765304:ios:356552ca97d13cf6b127cd',
    messagingSenderId: '1078431765304',
    projectId: 'flutter-chat-2b883',
    storageBucket: 'flutter-chat-2b883.appspot.com',
    iosClientId: '1078431765304-pehp0d36ns7t7bm1hvl6f4j62928fo4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
